name: myapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.6.0
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.2
  http_parser: ^4.0.1
  mime: ^2.0.0
  just_audio: ^0.9.39
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/audio/
